title: Revitalizing Monographs
#logo: /assets/img/logo.png
description: An NSF-sponsored series of workshops to revitalize monographic research.
show_downloads: false
#google_analytics:
theme: jekyll-theme-minimal
